### ISSUE TITLE
TYPING EFFECT NOT WORKING

### ISSUE THREAD

**Issue by dabbu-17** [dabbu-17/my-portfolio#1]
### **TYPING EFFECT ERROR**
There is some issue with the _typing effect_  . it is suppose to print the texts on screen which are mentioned on L2 @ Script.js , but its now working .
![image](https://github.com/user-attachments/assets/82b5118f-53d2-40b6-bba0-4685c6fc5037)
@aisanaul

**Comment by aiSanaul** [comment]
check if script file is linked in head, if it is then use "defer" at end of tag or move script inside body..
Example if its in head:
<script type="text/javascript" src="jquery-3.3.1.js" defer></script>
(remove defer if its in body)

**Comment by dabbu-17** [comment]
it works!
thanks (●'◡'●)

**Comment by dabbu-17** [comment]
it works!
thanks (●'◡'●)
@aiSanaul
